<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getAllArticle(){
        $query = $this->createQueryBuilder('a')
            ->innerJoin('a.tags','tags')
            ->innerJoin('tags.','tn')
            ->orderBy('a.id', 'ASC')
            ->getQuery()
            ->getResult();
        return $query;
    }
}
