<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getNames(){
        $query = $this->createQueryBuilder('t')
            ->select('t.name')
            ->getQuery()
            ->getResult();

        return $query;
    }
}
