# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.article_service:
        class: AppBundle\Services\ArticleService
        arguments: ['@doctrine']

    app.article_extension:
        class: AppBundle\Twig\ArticleExtension
        arguments: ['@app.article_service']
        tags:
            - { name: twig.extension }